[package]
name = "wsl-traffic-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Native Windows UI boundary for WSL Traffic Monitor."

[dependencies]
thiserror.workspace = true
tracing.workspace = true
wsl-traffic-core.workspace = true
wsl-traffic-monitor.workspace = true
wsl-traffic-diagnostics.workspace = true
wsl-traffic-storage.workspace = true
directories.workspace = true
wsl-traffic-windows.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse"
] }

[lints]
workspace = true
