[package]
name = "wsl-traffic-monitor"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Monitoring orchestration for WSL Traffic Monitor."

[dependencies]
thiserror.workspace = true
tracing.workspace = true
wsl-traffic-core.workspace = true
wsl-traffic-windows.workspace = true
wsl-traffic-wsl.workspace = true
time.workspace = true

[lints]
workspace = true
